[package]
name = "rust_lr"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
pyo3 = { version = "0.19.0", features = ["extension-module"] }

[lib]
name = "rust_lr"
crate-type = ["cdylib"]